export interface CalisthenicsExercise {
  name: string
  sets: number
  reps: string
  rest: string
  tips: string
  benefits: string[]
}

export interface CalisthenicsWorkout {
  id: string
  day: string
  duration: string
  time: string
  focus: string[]
  exercises: CalisthenicsExercise[]
  warmup: string[]
  cooldown: string[]
}

export const weeklyCalProgram: CalisthenicsWorkout[] = [
  {
    id: "cal_monday",
    day: "Segunda-feira",
    duration: "30 minutos",
    time: "12:00 - 12:30",
    focus: ["Peito", "Tríceps", "Abdômen"],
    warmup: ["Polichinelos - 2 min", "Rotação de braços - 1 min", "Alongamento dinâmico - 2 min"],
    exercises: [
      {
        name: "Flexões Tradicionais",
        sets: 4,
        reps: "15-20",
        rest: "45s",
        tips: "Corpo reto, desça até peito quase tocar o chão",
        benefits: ["Peito", "Tríceps", "Ombros"],
      },
      {
        name: "Flexões Diamante",
        sets: 3,
        reps: "10-15",
        rest: "60s",
        tips: "Mãos juntas formando diamante, foco nos tríceps",
        benefits: ["Tríceps", "Peito interno"],
      },
      {
        name: "Dips em Cadeira (Tríceps)",
        sets: 3,
        reps: "15-20",
        rest: "45s",
        tips: "Use uma cadeira, desça e suba com força dos tríceps",
        benefits: ["Tríceps", "Ombros"],
      },
      {
        name: "Prancha (Plank)",
        sets: 3,
        reps: "45-60s",
        rest: "30s",
        tips: "Corpo reto, abdômen contraído",
        benefits: ["Core completo", "Postura"],
      },
      {
        name: "Mountain Climbers",
        sets: 3,
        reps: "30 (15 cada perna)",
        rest: "30s",
        tips: "Rápido, queima gordura abdominal intensamente",
        benefits: ["Abdômen", "Cardio", "Queima gordura"],
      },
    ],
    cooldown: ["Alongamento de peito - 2 min", "Alongamento de tríceps - 1 min", "Respiração profunda - 2 min"],
  },
  {
    id: "cal_tuesday",
    day: "Terça-feira",
    duration: "30 minutos",
    time: "12:00 - 12:30",
    focus: ["Pernas", "Glúteos", "Cardio"],
    warmup: ["Corrida estacionária - 2 min", "Agachamento sem peso - 10x", "Mobilidade de quadril - 2 min"],
    exercises: [
      {
        name: "Agachamento Livre",
        sets: 4,
        reps: "20-25",
        rest: "60s",
        tips: "Desça bem profundo, joelhos alinhados com pés",
        benefits: ["Pernas", "Glúteos", "Core"],
      },
      {
        name: "Agachamento Búlgaro",
        sets: 3,
        reps: "12-15 cada perna",
        rest: "60s",
        tips: "Perna de trás elevada em cadeira, muito efetivo",
        benefits: ["Pernas", "Glúteos", "Equilíbrio"],
      },
      {
        name: "Afundo (Lunges)",
        sets: 3,
        reps: "12 cada perna",
        rest: "45s",
        tips: "Passo largo para frente, desça até joelho quase tocar chão",
        benefits: ["Pernas", "Glúteos"],
      },
      {
        name: "Jump Squats",
        sets: 3,
        reps: "15-20",
        rest: "60s",
        tips: "Agachamento explosivo com salto no final",
        benefits: ["Explosão", "Cardio", "Pernas"],
      },
      {
        name: "Burpees",
        sets: 3,
        reps: "12-15",
        rest: "45s",
        tips: "Exercício completo para queimar gordura rapidamente",
        benefits: ["Corpo todo", "Cardio intenso"],
      },
    ],
    cooldown: ["Alongamento de pernas - 3 min", "Alongamento de glúteos - 2 min"],
  },
  {
    id: "cal_wednesday",
    day: "Quarta-feira",
    duration: "30 minutos",
    time: "12:00 - 12:30",
    focus: ["Ombros", "Core", "Postura"],
    warmup: ["Rotação de ombros - 2 min", "Círculos com braços - 1 min", "Aquecimento dinâmico - 2 min"],
    exercises: [
      {
        name: "Pike Push-ups",
        sets: 4,
        reps: "12-15",
        rest: "60s",
        tips: "Quadril alto formando V invertido, desce a cabeça",
        benefits: ["Ombros", "Tríceps", "Core"],
      },
      {
        name: "Shoulder Taps (Prancha com toque)",
        sets: 3,
        reps: "20 (10 cada lado)",
        rest: "45s",
        tips: "Prancha alta, toque ombro oposto alternadamente",
        benefits: ["Ombros", "Core", "Estabilidade"],
      },
      {
        name: "Prancha Lateral",
        sets: 3,
        reps: "30-45s cada lado",
        rest: "30s",
        tips: "Corpo reto de lado, oblíquos trabalham intensamente",
        benefits: ["Oblíquos", "Core lateral"],
      },
      {
        name: "Superman",
        sets: 3,
        reps: "15-20",
        rest: "45s",
        tips: "Deitado de barriga, eleve braços e pernas simultaneamente",
        benefits: ["Lombar", "Postura", "Core posterior"],
      },
      {
        name: "Russian Twists (torção russa)",
        sets: 3,
        reps: "30 (15 cada lado)",
        rest: "30s",
        tips: "Sentado, pés elevados, torça o tronco lado a lado",
        benefits: ["Oblíquos", "Rotação", "Abdômen"],
      },
    ],
    cooldown: ["Alongamento de ombros - 2 min", "Mobilidade de coluna - 2 min", "Respiração - 1 min"],
  },
  {
    id: "cal_thursday",
    day: "Quinta-feira",
    duration: "DESCANSO",
    time: "-",
    focus: ["Recuperação"],
    warmup: [],
    exercises: [],
    cooldown: [],
  },
  {
    id: "cal_friday",
    day: "Sexta-feira",
    duration: "30 minutos",
    time: "12:00 - 12:30",
    focus: ["Abdômen", "Core", "Queima de gordura"],
    warmup: ["Prancha - 30s", "Bicicleta no ar - 1 min", "Mobilidade - 2 min"],
    exercises: [
      {
        name: "Leg Raises (Elevação de pernas)",
        sets: 4,
        reps: "15-20",
        rest: "45s",
        tips: "Deitado, pernas retas até 90 graus - abdômen inferior",
        benefits: ["Abdômen inferior", "Hip flexors"],
      },
      {
        name: "Bicicleta no Ar",
        sets: 4,
        reps: "30 (15 cada lado)",
        rest: "30s",
        tips: "Cotovelo toca joelho oposto, movimento controlado",
        benefits: ["Oblíquos", "Abdômen completo"],
      },
      {
        name: "V-Ups",
        sets: 3,
        reps: "12-15",
        rest: "60s",
        tips: "Forma V com corpo, mãos tocam pés",
        benefits: ["Abdômen completo", "Hip flexors"],
      },
      {
        name: "Prancha com elevação de perna",
        sets: 3,
        reps: "20 (10 cada perna)",
        rest: "45s",
        tips: "Prancha, eleve uma perna de cada vez",
        benefits: ["Core", "Glúteos", "Estabilidade"],
      },
      {
        name: "Burpees",
        sets: 3,
        reps: "15-20",
        rest: "60s",
        tips: "Máxima intensidade para finalizar a semana forte",
        benefits: ["Cardio", "Queima gordura", "Corpo todo"],
      },
    ],
    cooldown: ["Alongamento completo - 3 min", "Respiração profunda - 2 min"],
  },
  {
    id: "cal_saturday",
    day: "Sábado",
    duration: "60 minutos",
    time: "Horário livre",
    focus: ["Full Body", "Força", "Resistência", "Queima máxima"],
    warmup: ["Polichinelos - 3 min", "Burpees leves - 10x", "Rotação completa - 2 min", "Mobilidade articular - 3 min"],
    exercises: [
      {
        name: "Flexões (variações: tradicional, diamante, larga)",
        sets: 5,
        reps: "20-25",
        rest: "60s",
        tips: "Faça séries variando os tipos de flexão",
        benefits: ["Peito", "Tríceps", "Ombros"],
      },
      {
        name: "Agachamento + Jump Squats",
        sets: 5,
        reps: "25 + 10 saltos",
        rest: "90s",
        tips: "Combine agachamentos normais com saltos explosivos",
        benefits: ["Pernas", "Explosão", "Cardio"],
      },
      {
        name: "Pike Push-ups",
        sets: 4,
        reps: "15-20",
        rest: "60s",
        tips: "Foco total nos ombros",
        benefits: ["Ombros", "Tríceps"],
      },
      {
        name: "Leg Raises",
        sets: 4,
        reps: "20-25",
        rest: "45s",
        tips: "Controle total no movimento",
        benefits: ["Abdômen inferior"],
      },
      {
        name: "Afundos Caminhando",
        sets: 4,
        reps: "20 (10 cada perna)",
        rest: "60s",
        tips: "Caminhe fazendo afundos pelo espaço disponível",
        benefits: ["Pernas", "Glúteos", "Equilíbrio"],
      },
      {
        name: "Dips em Cadeira",
        sets: 4,
        reps: "20-25",
        rest: "60s",
        tips: "Desça bem profundo",
        benefits: ["Tríceps", "Ombros"],
      },
      {
        name: "Prancha (todas variações)",
        sets: 3,
        reps: "60s frontal + 30s cada lado",
        rest: "60s",
        tips: "Frontal, depois lateral esquerda, depois direita",
        benefits: ["Core completo"],
      },
      {
        name: "Burpees FINALIZADOR",
        sets: 4,
        reps: "20-25",
        rest: "90s",
        tips: "Máxima intensidade para finalizar o treino",
        benefits: ["Cardio explosivo", "Queima máxima"],
      },
    ],
    cooldown: [
      "Alongamento completo de todo corpo - 5 min",
      "Mobilidade articular - 3 min",
      "Respiração e relaxamento - 2 min",
    ],
  },
  {
    id: "cal_sunday",
    day: "Domingo",
    duration: "DESCANSO",
    time: "-",
    focus: ["Recuperação total", "Descanso ativo (caminhada leve opcional)"],
    warmup: [],
    exercises: [],
    cooldown: [],
  },
]
