-- Tabela para horários de Ginástica (Sala de Ginástica)
CREATE TABLE IF NOT EXISTS ginastica_schedule (
  id SERIAL PRIMARY KEY,
  time_slot VARCHAR(10) NOT NULL,
  monday VARCHAR(100),
  tuesday VARCHAR(100),
  wednesday VARCHAR(100),
  thursday VARCHAR(100),
  friday VARCHAR(100),
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Inserir dados da grade de ginástica
INSERT INTO ginastica_schedule (time_slot, monday, tuesday, wednesday, thursday, friday) VALUES
('6:00', NULL, 'JUMP - KARINA', NULL, 'JUMP - KARINA', NULL),
('7:00', 'PILATES - ALEX', NULL, 'PILATES - ALEX', NULL, 'PILATES - ALEX'),
('7:15', NULL, 'FITDANCE - THAIS', NULL, 'FITDANCE - THAIS', NULL),
('7:30', 'ALLP ZONE - JAQUELINE', NULL, 'ALLP ZONE - JAQUELINE', NULL, 'ALLP ZONE - JAQUELINE'),
('8:00', 'GAP - RENATO', 'MUAY THAI - NICOLAS', 'RITBOX - RENATO', 'MUAY THAI - NICOLAS', 'GAP - RENATO'),
('8:45', 'FITDANCE - RENATO', NULL, 'FITDANCE - RENATO', NULL, 'FITDANCE - RENATO'),
('9:15', NULL, 'GAP - ARILDO', NULL, 'GAP - ARILDO', NULL),
('9:30', 'ABDÔMEN - RENATO', NULL, 'ABDÔMEN - RENATO', NULL, 'ABDÔMEN - RENATO'),
('16:00', 'ABDOMINAL - ZAIRA', NULL, 'ABDOMINAL - ZAIRA', NULL, NULL),
('18:00', NULL, 'MUAY THAI - NICOLAS', NULL, 'MUAY THAI - NICOLAS', NULL),
('18:15', 'ABDOMINAL - ZAIRA', NULL, 'ABDOMINAL ZAIRA', NULL, 'MUAY THAI - NICOLAS'),
('18:30', NULL, 'ALLP ZONE - JAQUELINE', NULL, 'ALLP ZONE - JAQUELINE', NULL),
('19:00', 'STEP - ZAIRA', 'FITDANCE - ALEX', 'STEP - ZAIRA', 'FITDANCE - ALEX', NULL),
('19:15', NULL, NULL, NULL, NULL, 'FITDANCE - ALEX'),
('19:45', 'FITDANCE - ZAIRA', NULL, 'FITDANCE - ZAIRA', NULL, NULL),
('20:00', NULL, 'GAP - JAQUE', NULL, 'GAP - JAQUE', NULL),
('20:30', 'PILATES - ALEX', NULL, 'PILATES - ALEX', NULL, NULL),
('20:45', NULL, 'JUMP - KARINA', NULL, 'JUMP - KARINA', NULL)
ON CONFLICT DO NOTHING;
