-- Posts 1-3 Saúde + 10 Qualidade de Vida
INSERT INTO blog_posts (category_id, title, slug, excerpt, content, author) VALUES
(5, 'Saúde Mental e Exercício Físico', 'saude-mental-exercicio-fisico', 'Como o treino melhora seu bem-estar psicológico', 'Exercício libera endorfina, reduz ansiedade e depressão, melhora autoestima e qualidade do sono. É terapia natural. Personal trainers e academias promovem saúde integral. A FitTransform ajuda profissionais a acompanhar bem-estar completo dos alunos.', 'Equipe FitTransform'),
(5, 'Importância do Check-up Médico Antes de Treinar', 'checkup-medico-antes-treinar', 'Segurança em primeiro lugar', 'Avaliação médica identifica restrições e garante segurança. Exames cardiológicos, ortopédicos e laboratoriais são importantes. Personal trainers solicitam liberação médica antes de iniciar treinos intensos. Registre histórico de saúde na FitTransform.', 'Equipe FitTransform'),
(5, 'Exercícios para Terceira Idade', 'exercicios-terceira-idade', 'Envelheça com saúde e qualidade de vida', 'Idosos se beneficiam de exercícios de baixo impacto, força, equilíbrio e alongamento. Previnem quedas, mantêm independência e melhoram qualidade de vida. A FitTransform permite criar programas específicos para todas as idades.', 'Equipe FitTransform'),

(5, 'Rotina Matinal para Produtividade', 'rotina-matinal-produtividade', 'Comece o dia com energia e foco', 'Acorde cedo, hidrate-se, exercite-se, medite, planeje o dia. Exercício pela manhã aumenta energia e foco. Personal trainers podem agendar treinos matinais para clientes que buscam produtividade. Gerencie horários na FitTransform.', 'Equipe FitTransform'),
(5, 'Sono de Qualidade: Aliado dos Seus Resultados', 'sono-qualidade-resultados', 'Recupere-se adequadamente para progredir', '7-9h de sono são essenciais para recuperação muscular, hormônios e performance. Evite telas antes de dormir, mantenha rotina. Personal trainers orientam sobre importância do descanso. Monitore frequência de treinos na FitTransform para evitar overtraining.', 'Equipe FitTransform'),
(5, 'Gerenciamento de Estresse com Exercício', 'gerenciamento-estresse-exercicio', 'Reduza tensão e ansiedade através do movimento', 'Exercício é poderoso anti-estresse. Libera tensões, melhora humor, promove relaxamento. Yoga, caminhada e treinos moderados são especialmente eficazes. Ofereça modalidades variadas aos alunos através da FitTransform.', 'Equipe FitTransform'),
(5, 'Equilíbrio Trabalho-Vida-Treino', 'equilibrio-trabalho-vida-treino', 'Organize sua rotina para ter tempo para saúde', 'Priorize saúde, planeje treinos, seja eficiente. 30-45min 3-4x/semana são suficientes. Treinos curtos e intensos economizam tempo. Personal trainers criam programas flexíveis adaptados à rotina de cada cliente na FitTransform.', 'Equipe FitTransform'),
(5, 'Mindfulness e Exercício: Treino Consciente', 'mindfulness-exercicio-treino-consciente', 'Esteja presente durante seus treinos', 'Treinar com atenção plena melhora conexão mente-músculo, técnica e resultados. Evite distrações, foque no movimento, respire conscientemente. Personal trainers ensinam execução correta e consciência corporal.', 'Equipe FitTransform'),
(5, 'Objetivos SMART para Fitness', 'objetivos-smart-fitness', 'Defina metas claras e alcançáveis', 'Específico, Mensurável, Atingível, Relevante, Temporal. Ex: "Perder 5kg em 3 meses" vs "Emagrecer". A FitTransform permite definir e acompanhar objetivos mensuráveis de cada aluno com gráficos de progresso.', 'Equipe FitTransform'),
(5, 'Consistência: Segredo do Sucesso no Fitness', 'consistencia-segredo-sucesso-fitness', 'Resultados vêm com dedicação contínua', 'Treinar regularmente supera treinos esporádicos intensos. Crie hábitos, seja paciente, celebre pequenas vitórias. A jornada é longa. Personal trainers motivam e acompanham alunos via FitTransform para manter constância.', 'Equipe FitTransform'),
(5, 'Comunidade Fitness: Encontre Seu Grupo', 'comunidade-fitness-encontre-grupo', 'Apoio social potencializa resultados', 'Treinar com amigos, grupos ou comunidades aumenta motivação e aderência. Academias e personal trainers criam senso de comunidade. A FitTransform facilita comunicação e engajamento entre profissionais e alunos.', 'Equipe FitTransform'),
(5, 'Transformação de Vida: Histórias Reais', 'transformacao-vida-historias-reais', 'Inspire-se com quem transformou saúde e vida', 'Compartilhar histórias de sucesso motiva outros. Alunos que emagreceram, ganharam saúde, superaram desafios. Personal trainers e academias celebram conquistas. A FitTransform acompanha toda jornada de transformação dos alunos com fotos, medidas e evolução.', 'Equipe FitTransform'),
(5, 'Autocuidado: Priorize Sua Saúde', 'autocuidado-priorize-saude', 'Você merece cuidar de si mesmo', 'Autocuidado não é egoísmo. Exercite-se, alimente-se bem, descanse, faça o que gosta. Saúde física e mental caminham juntas. A FitTransform é ferramenta para profissionais que se importam com o bem-estar completo de seus clientes.', 'Equipe FitTransform'),
(5, 'FitTransform: Tecnologia a Serviço da Sua Saúde', 'fittransform-tecnologia-saude', 'Como nossa plataforma transforma vidas', 'A FitTransform conecta academias, personal trainers e alunos em um ecossistema integrado. Gestão completa, treinos personalizados, acompanhamento de resultados, comunicação eficiente. Tecnologia que realmente faz diferença na vida das pessoas. Experimente gratuitamente!', 'Equipe FitTransform')
ON CONFLICT (slug) DO NOTHING;
