-- Posts 1-9 Hidratação
INSERT INTO blog_posts (category_id, title, slug, excerpt, content, author) VALUES
(3, 'Importância da Hidratação Durante o Treino', 'importancia-hidratacao-treino', 'Água é fundamental para performance e saúde', 'A desidratação reduz performance, causa cãibras e pode ser perigosa. Beba 500ml 2h antes, 200ml a cada 15-20min durante e reponha após. Na FitTransform, personal trainers podem definir metas de consumo de água para cada treino e aluno.', 'Equipe FitTransform'),
(3, 'Quanto de Água Você Precisa Beber Por Dia?', 'quanto-agua-beber-dia', 'Calcule sua necessidade hídrica individual', 'A recomendação geral é 35ml/kg de peso corporal, mas varia com atividade física, clima e saúde. Quem treina precisa de mais. Monitore a cor da urina e sede. A FitTransform permite registrar consumo diário de água dos alunos.', 'Equipe FitTransform'),
(3, 'Isotônicos vs Água: Quando Usar Cada Um?', 'isotonico-vs-agua', 'Entenda qual bebida escolher para cada situação', 'Água é suficiente para treinos até 60min. Isotônicos repõem eletrólitos em atividades mais longas ou intensas. Evite bebidas açucaradas. Personal trainers podem orientar sobre hidratação ideal via FitTransform baseado no tipo e duração do treino.', 'Equipe FitTransform'),
(3, 'Desidratação: Sinais e Como Prevenir', 'desidratacao-sinais-prevenir', 'Reconheça os sintomas e mantenha-se hidratado', 'Sinais de desidratação: sede intensa, urina escura, tontura, fadiga, cãibras. Previna bebendo água regularmente ao longo do dia. Registre a hidratação dos seus alunos na FitTransform para garantir que estão bebendo água suficiente.', 'Equipe FitTransform'),
(3, 'Hidratação e Performance Esportiva', 'hidratacao-performance-esportiva', 'Como a água afeta seu desempenho nos treinos', 'Apenas 2% de desidratação reduz performance em até 20%. A água regula temperatura corporal, transporta nutrientes e elimina toxinas. Mantenha-se bem hidratado para treinos mais eficientes. Use a FitTransform para educar seus alunos sobre hidratação.', 'Equipe FitTransform'),
(3, 'Água com Limão: Benefícios para Quem Treina', 'agua-limao-beneficios-treino', 'Potencialize sua hidratação com limão', 'Água com limão em jejum alcaliniza o corpo, melhora digestão e fornece vitamina C. É hidratante e refrescante. Não substitui refeições. Personal trainers podem sugerir receitas saudáveis de bebidas aos alunos pela FitTransform.', 'Equipe FitTransform'),
(3, 'Água de Coco: Hidratação Natural Pós-Treino', 'agua-coco-hidratacao-natural', 'Reposição natural de eletrólitos', 'Água de coco é rica em potássio e magnésio, sendo excelente pós-treino. É natural, pouco calórica e hidrata eficientemente. Combine com uma refeição proteica. Registre orientações nutricionais personalizadas na FitTransform.', 'Equipe FitTransform'),
(3, 'Mitos e Verdades Sobre Hidratação', 'mitos-verdades-hidratacao', 'Descubra o que é fato e o que é mito', 'Mito: Água gelada engorda. Verdade: Temperatura não afeta calorias. Mito: Chás e cafés desidratam. Verdade: Contribuem para hidratação, mas com moderação. Eduque seus alunos com informações corretas usando a FitTransform.', 'Equipe FitTransform'),
(3, 'Aplicativos de Hidratação e a FitTransform', 'apps-hidratacao-fittransform', 'Tecnologia a favor da sua saúde', 'Monitorar ingestão de água ficou fácil. A FitTransform permite que personal trainers definam metas de hidratação por treino e acompanhem o cumprimento. Combine tecnologia com orientação profissional para melhores resultados.', 'Equipe FitTransform')
ON CONFLICT (slug) DO NOTHING;
