-- Posts 1-4 Corrida + 5 Caminhada
INSERT INTO blog_posts (category_id, title, slug, excerpt, content, author) VALUES
(5, 'Guia do Iniciante: Como Começar a Correr', 'guia-iniciante-comecar-correr', 'Primeiros passos para se tornar um corredor', 'Comece caminhando, alterne caminhada/corrida, aumente gradualmente. Use tênis adequado, alongue, hidrate. Respeite limites. Na FitTransform, personal trainers criam programas de corrida progressivos e acompanham evolução de distância e tempo dos alunos.', 'Equipe FitTransform'),
(5, 'Treino Intervalado (HIIT) na Corrida', 'treino-intervalado-hiit-corrida', 'Queime mais calorias em menos tempo', 'HIIT alterna alta e baixa intensidade. Ex: 1min forte + 2min leve por 20min. Melhora condicionamento, queima gordura e economiza tempo. Personal trainers programam treinos HIIT personalizados na FitTransform por modalidade e local.', 'Equipe FitTransform'),
(5, 'Corrida de Rua vs Esteira: Prós e Contras', 'corrida-rua-vs-esteira', 'Qual modalidade escolher para seus treinos?', 'Rua: ar livre, terreno variado, mais desafiador. Esteira: controle total, clima, segurança. Ambas são válidas. Varie para melhores resultados. Registre todas as modalidades de treino dos alunos na FitTransform.', 'Equipe FitTransform'),
(5, 'Prevenção de Lesões na Corrida', 'prevencao-lesoes-corrida', 'Corra com segurança e longevidade', 'Aquecimento, tênis adequado, progressão gradual, fortalecimento muscular e descanso previnem lesões. Ouça seu corpo. Personal trainers monitoram frequência e intensidade dos treinos via FitTransform para prevenir overtraining.', 'Equipe FitTransform'),

(5, 'Benefícios da Caminhada para a Saúde', 'beneficios-caminhada-saude', 'Exercício simples com grandes resultados', 'Caminhar melhora saúde cardiovascular, controla peso, reduz estresse e é acessível a todos. 30min/dia já trazem benefícios. Personal trainers podem prescrever caminhadas como atividade complementar ou principal na FitTransform.', 'Equipe FitTransform'),
(5, 'Caminhada Rápida vs Corrida Leve', 'caminhada-rapida-vs-corrida-leve', 'Qual queima mais calorias?', 'Corrida leve queima mais calorias, mas caminhada rápida (6km/h+) é excelente alternativa de baixo impacto. Ambas melhoram condicionamento. Escolha segundo seu nível e objetivos. Monitore progressão na FitTransform.', 'Equipe FitTransform'),
(5, 'Como Aumentar Velocidade na Caminhada', 'aumentar-velocidade-caminhada', 'Evolua gradualmente para melhores resultados', 'Aumente velocidade progressivamente, mantenha postura ereta, use braços, varie terrenos. Treinos intervalados também funcionam na caminhada. Personal trainers ajustam intensidade dos treinos semanalmente usando a FitTransform.', 'Equipe FitTransform'),
(5, 'Caminhada em Grupo: Motivação Extra', 'caminhada-grupo-motivacao', 'Exercite-se socialmente e mantenha constância', 'Caminhar em grupo aumenta aderência, torna o exercício social e motivador. Academias e personal trainers podem organizar grupos de caminhada. Gerencie eventos e atividades em grupo através da FitTransform.', 'Equipe FitTransform'),
(5, 'Técnica Correta de Caminhada', 'tecnica-correta-caminhada', 'Caminhe de forma eficiente e segura', 'Postura ereta, olhar à frente, braços em 90°, passo natural, calcanhar primeiro. Respiração ritmada. Evite celular durante caminhada. Personal trainers orientam técnica adequada e prescrevem treinos personalizados na FitTransform.', 'Equipe FitTransform')
ON CONFLICT (slug) DO NOTHING;
